# peregrine - zero-dependency bootstrap build (host arch only)
#
# The real build is Meson (see meson.build). This Makefile exists so you can
# compile and run the worked kernel + checkasm with nothing but a C compiler:
#
#     make -f Makefile.bootstrap test
#
# It builds the CPU C code plus the hand-written asm for the HOST arch only
# (NEON on aarch64, AVX2 via nasm on x86_64). Cross-arch is Meson's job.

CC      ?= cc
CFLAGS  ?= -O3 -Wall -Wextra -std=c11 -D_POSIX_C_SOURCE=200809L -pthread -Iinclude -Isrc
LDLIBS  ?= -lm -pthread

UNAME_M := $(shell uname -m)

C_SRC := \
  src/util/cpu.c \
  src/util/mem.c \
  src/util/filemap.c \
  src/util/thread.c \
  src/model/model_file.c \
  src/tensor/kernels/dot/dot_ref.c \
  src/tensor/kernels/dot/dot_init.c \
  src/tensor/kernels/axpy/axpy_ref.c \
  src/tensor/kernels/axpy/axpy_init.c \
  src/tensor/kernels/rmsnorm/rmsnorm_ref.c \
  src/tensor/kernels/rmsnorm/rmsnorm_init.c \
  src/tensor/kernels/sum/sum_ref.c \
  src/tensor/kernels/sum/sum_init.c \
  src/tensor/kernels/max/max_ref.c \
  src/tensor/kernels/max/max_init.c \
  src/tensor/kernels/mul/mul_ref.c \
  src/tensor/kernels/mul/mul_init.c \
  src/tensor/kernels/add/add_ref.c \
  src/tensor/kernels/add/add_init.c \
  src/tensor/kernels/silu/silu_ref.c \
  src/tensor/kernels/silu/silu_init.c \
  src/tensor/kernels/gelu/gelu_ref.c \
  src/tensor/kernels/gelu/gelu_init.c \
  src/tensor/kernels/softmax/softmax_ref.c \
  src/tensor/kernels/softmax/softmax_init.c \
  src/tensor/kernels/rope/rope_ref.c \
  src/tensor/kernels/rope/rope_init.c \
  src/tensor/kernels/gemm/gemm_ref.c \
  src/tensor/kernels/gemm/gemm_init.c \
  src/tensor/kernels/gemm/gemm_blocked.c \
  src/tensor/kernels/gemv/gemv_ref.c \
  src/tensor/kernels/gemv/gemv_init.c \
  src/tensor/kernels/gemv/gemv_driver.c \
  src/tensor/kernels/gemm/gemm_bf16.c \
  src/tensor/kernels/gemm/gemm_bf16_init.c \
  src/tensor/kernels/gemm/gemm_fp16.c \
  src/tensor/kernels/gemm/gemm_fp16_init.c \
  src/tensor/kernels/exp/exp_ref.c \
  src/tensor/kernels/exp/exp_init.c

OBJ := $(C_SRC:.c=.o)

# --- host-arch assembly --------------------------------------------------
# CHECK_ASM is the checkasm register-clobber trampoline for the host arch.
ifneq (,$(filter arm64 aarch64,$(UNAME_M)))
  # clang/gcc assemble .S directly (runs the C preprocessor for our macros)
  ASM_OBJ := \
    src/tensor/kernels/dot/arm/dot_neon.o \
    src/tensor/kernels/axpy/arm/axpy_neon.o \
    src/tensor/kernels/rmsnorm/arm/rmsnorm_neon.o \
    src/tensor/kernels/sum/arm/sum_neon.o \
    src/tensor/kernels/max/arm/max_neon.o \
    src/tensor/kernels/mul/arm/mul_neon.o \
    src/tensor/kernels/add/arm/add_neon.o \
    src/tensor/kernels/exp/arm/exp_neon.o \
    src/tensor/kernels/silu/arm/silu_neon.o \
    src/tensor/kernels/gelu/arm/gelu_neon.o \
    src/tensor/kernels/softmax/arm/softmax_neon.o \
    src/tensor/kernels/rope/arm/rope_neon.o \
    src/tensor/kernels/gemm/gemm_neon.o \
    src/tensor/kernels/gemm/arm/sgemm_ukernel_neon.o \
    src/tensor/kernels/gemv/gemv_neon.o \
    src/tensor/kernels/gemm/gemm_bf16_neon.o \
    src/tensor/kernels/gemm/gemm_bf16_mmla.o \
    src/tensor/kernels/gemm/arm/bf16gemm_ukernel_neon.o \
    src/tensor/kernels/gemm/gemm_fp16_neon.o \
    src/tensor/kernels/gemm/gemm_fp16_f16.o \
    src/tensor/kernels/gemm/arm/fp16gemm_ukernel_neon.o
  CHECK_ASM := tests/checkasm/arm/checkasm.S
%.o: %.S
	$(CC) $(CFLAGS) -c $< -o $@
endif

ifeq ($(UNAME_M),x86_64)
  NASM ?= nasm
  ifeq ($(shell uname -s),Darwin)
    NASMFMT := macho64
  else
    NASMFMT := elf64
  endif
  ASM_OBJ := \
    src/tensor/kernels/dot/x86/dot_avx2.o \
    src/tensor/kernels/axpy/x86/axpy_avx2.o \
    src/tensor/kernels/rmsnorm/x86/rmsnorm_avx2.o \
    src/tensor/kernels/sum/x86/sum_avx2.o \
    src/tensor/kernels/max/x86/max_avx2.o \
    src/tensor/kernels/mul/x86/mul_avx2.o \
    src/tensor/kernels/add/x86/add_avx2.o \
    src/tensor/kernels/exp/x86/exp_avx2.o \
    src/tensor/kernels/silu/x86/silu_avx2.o \
    src/tensor/kernels/gelu/x86/gelu_avx2.o \
    src/tensor/kernels/softmax/x86/softmax_avx2.o \
    src/tensor/kernels/gemm/gemm_avx2.o \
    src/tensor/kernels/gemm/x86/sgemm_ukernel_avx2.o \
    src/tensor/kernels/gemv/gemv_avx2.o \
    src/tensor/kernels/gemm/gemm_bf16_avx2.o \
    src/tensor/kernels/gemm/gemm_bf16_avx512bf16.o \
    src/tensor/kernels/gemm/x86/bf16gemm_ukernel_avx512bf16.o \
    src/tensor/kernels/gemm/gemm_fp16_avx2.o
  CHECK_ASM := tests/checkasm/x86/checkasm.o
%.o: %.asm
	$(NASM) -f $(NASMFMT) -I src/ $< -o $@
endif

# --- targets -------------------------------------------------------------
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

CHECK_SRC := \
  tests/checkasm/checkasm.c \
  tests/checkasm/checkasm_dot.c \
  tests/checkasm/checkasm_axpy.c \
  tests/checkasm/checkasm_rmsnorm.c \
  tests/checkasm/checkasm_sum.c \
  tests/checkasm/checkasm_max.c \
  tests/checkasm/checkasm_mul.c \
  tests/checkasm/checkasm_add.c \
  tests/checkasm/checkasm_silu.c \
  tests/checkasm/checkasm_gelu.c \
  tests/checkasm/checkasm_softmax.c \
  tests/checkasm/checkasm_rope.c \
  tests/checkasm/checkasm_exp.c \
  tests/checkasm/checkasm_gemm.c \
  tests/checkasm/checkasm_gemv.c \
  tests/checkasm/checkasm_gemm_bf16.c \
  tests/checkasm/checkasm_gemm_fp16.c

peregrine: src/cli/peregrine.c $(OBJ) $(ASM_OBJ)
	$(CC) $(CFLAGS) $^ $(LDLIBS) -o $@

checkasm: $(CHECK_SRC) $(CHECK_ASM) $(OBJ) $(ASM_OBJ)
	$(CC) $(CFLAGS) -Itests/checkasm $^ $(LDLIBS) -o $@

.PHONY: test bench clean
test: checkasm
	./checkasm

bench: checkasm
	./checkasm --bench

clean:
	rm -f $(OBJ) $(ASM_OBJ) tests/checkasm/x86/checkasm.o peregrine checkasm
