#ifndef PEREGRINE_VERSION_H
#define PEREGRINE_VERSION_H

#define PEREGRINE_VERSION_MAJOR 0
#define PEREGRINE_VERSION_MINOR 1
#define PEREGRINE_VERSION_PATCH 0
#define PEREGRINE_VERSION_STRING "0.1.0"

#endif /* PEREGRINE_VERSION_H */
